import Head from "next/head";
import { Inter } from "next/font/google";
import { GlobalStyled } from "@/styles/Global.Styled";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const getData = async () => {
    const response = await fetch("/api");
    const data = await response.json();
    console.log(data);
  };
  getData();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <GlobalStyled />
      <h1>giorgi</h1>
    </>
  );
}
